-- MySQL Script generated by MySQL Workbench
-- Thu Dec 14 16:07:03 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mutual
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mutual
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mutual` DEFAULT CHARACTER SET utf8 ;
USE `mutual` ;

-- -----------------------------------------------------
-- Table `mutual`.`estadoContactos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mutual`.`estadoContactos` (
  `idEstado` INT NOT NULL,
  `tipoEstado` VARCHAR(11) NOT NULL COMMENT 'Indica el estado de la consulta\n- Enviado\n- En revisión\n- Cerrado',
  PRIMARY KEY (`idEstado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mutual`.`Clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mutual`.`Clientes` (
  `rutCliente` VARCHAR(10) NOT NULL,
  `nombreCliente` VARCHAR(32) NOT NULL,
  `apellidoCliente` VARCHAR(64) NOT NULL,
  `email` VARCHAR(192) NOT NULL,
  `telefono` INT NULL,
  PRIMARY KEY (`rutCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mutual`.`Contactos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mutual`.`Contactos` (
  `idContacto` INT NOT NULL AUTO_INCREMENT,
  `mensaje` TEXT(500) NOT NULL,
  `estado` INT NOT NULL,
  `rutCliente` VARCHAR(10) NOT NULL,
  `Clientes_rutCliente` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`idContacto`),
  INDEX `fk_estadoContacto_idx` (`estado` ASC),
  INDEX `fk_Contactos_Clientes1_idx` (`Clientes_rutCliente` ASC),
  CONSTRAINT `fk_estadoContacto`
    FOREIGN KEY (`estado`)
    REFERENCES `mutual`.`estadoContactos` (`idEstado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Contactos_Clientes1`
    FOREIGN KEY (`Clientes_rutCliente`)
    REFERENCES `mutual`.`Clientes` (`rutCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mutual`.`Simulaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mutual`.`Simulaciones` (
  `idCredito` INT NOT NULL AUTO_INCREMENT,
  `ingresoMensual` INT NOT NULL,
  `montoSolicitado` INT NOT NULL DEFAULT 500000,
  `numeroCuotas` INT NOT NULL DEFAULT 6,
  `tasaInteres` INT NOT NULL DEFAULT 4,
  `degravamen` TINYINT NOT NULL DEFAULT 1,
  `accidentes` TINYINT NULL DEFAULT 0,
  `cesantia` TINYINT NULL DEFAULT 0,
  `fechaSimulacion` DATE NULL,
  `rutCliente` VARCHAR(10) NOT NULL,
  `Clientes_rutCliente` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`idCredito`),
  INDEX `fk_Simulaciones_Clientes1_idx` (`Clientes_rutCliente` ASC),
  CONSTRAINT `fk_Simulaciones_Clientes1`
    FOREIGN KEY (`Clientes_rutCliente`)
    REFERENCES `mutual`.`Clientes` (`rutCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `mutual`.`estadoContactos`
-- -----------------------------------------------------
START TRANSACTION;
USE `mutual`;
INSERT INTO `mutual`.`estadoContactos` (`idEstado`, `tipoEstado`) VALUES (1, 'Enviado');
INSERT INTO `mutual`.`estadoContactos` (`idEstado`, `tipoEstado`) VALUES (2, 'En Revision');
INSERT INTO `mutual`.`estadoContactos` (`idEstado`, `tipoEstado`) VALUES (3, 'Cerrado');

COMMIT;

