-- MySQL Script generated by MySQL Workbench
-- Wed Dec 13 16:21:57 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`estadoContactos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`estadoContactos` (
  `idEstado` INT NOT NULL,
  `tipoEstado` VARCHAR(11) NOT NULL COMMENT 'Indica el estado de la consulta\n- Enviado\n- En revisión\n- Cerrado',
  PRIMARY KEY (`idEstado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Clientes` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `rutCliente` VARCHAR(10) NOT NULL,
  `nombreCliente` VARCHAR(32) NOT NULL,
  `apellidoCliente` VARCHAR(64) NOT NULL,
  `email` VARCHAR(192) NOT NULL,
  `telefono` INT NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Contactos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Contactos` (
  `idContacto` INT NOT NULL AUTO_INCREMENT,
  `mensaje` TEXT(500) NOT NULL,
  `estado` INT NOT NULL,
  `rutCliente` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`idContacto`),
  INDEX `fk_estadoContacto_idx` (`estado` ASC),
  INDEX `fk_clienteContacto_idx` (`rutCliente` ASC),
  CONSTRAINT `fk_estadoContacto`
    FOREIGN KEY (`estado`)
    REFERENCES `mydb`.`estadoContactos` (`idEstado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_clienteContacto`
    FOREIGN KEY (`rutCliente`)
    REFERENCES `mydb`.`Clientes` (`rutCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Simulaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Simulaciones` (
  `idCredito` INT NOT NULL AUTO_INCREMENT,
  `ingresoMensual` INT NOT NULL,
  `montoSolicitado` INT NOT NULL DEFAULT 500000,
  `numeroCuotas` INT NOT NULL DEFAULT 6,
  `tasaInteres` INT NOT NULL DEFAULT 4,
  `degravamen` TINYINT NOT NULL DEFAULT 1,
  `accidentes` TINYINT NULL DEFAULT 0,
  `cesantia` TINYINT NULL DEFAULT 0,
  `fechaSimulacion` DATE NULL,
  `idCliente` INT NOT NULL,
  PRIMARY KEY (`idCredito`),
  INDEX `fk_rutCliente-simulacion_idx` (`idCliente` ASC),
  CONSTRAINT `fk_rutCliente-simulacion`
    FOREIGN KEY (`idCliente`)
    REFERENCES `mydb`.`Clientes` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `mydb`.`estadoContactos`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`estadoContactos` (`idEstado`, `tipoEstado`) VALUES (1, 'Enviado');
INSERT INTO `mydb`.`estadoContactos` (`idEstado`, `tipoEstado`) VALUES (2, 'En Revision');
INSERT INTO `mydb`.`estadoContactos` (`idEstado`, `tipoEstado`) VALUES (3, 'Cerrado');

COMMIT;

